apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "template.fullname" . }}
  labels:
    app: {{ template "template.name" . }}
    chart: {{ template "template.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "template.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "template.name" . }}
        release: {{ .Release.Name }}
      annotations:
        # consul.*/ annotations will register your service in consul
        # for service discovery.
        consul.register/enabled: "true"
        consul.register/pod.container.name: "{{ .Chart.Name }}"
        consul.register/service.name: "sa-tools-integrations-docs"
        {{- if .Values.iamRole }}
        iam.amazonaws.com/role: "{{ .Values.iamRole }}"
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.image.override }}
          image: '{{ .Values.image.override }}'
          {{- else }}
          image: '{{ .Values.image.registry }}/{{ .Values.image.repo }}:{{ .Values.image.tag }}'
          {{- end }}
          ports:
            # TODO: Use a more informative port name.
            - name: port0
              containerPort: 8000
          {{- if not .Values.runAsRoot }}
          securityContext:
            runAsUser: 65534
            allowPrivilegeEscalation: false
          {{- end }}
          env:
            - name: MSG_HEALTH_TOPIC
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            {{- range $key, $value := .Values.environment }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
{{ toYaml .Values.readinessProbe | trimSuffix "\n" | indent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
{{ toYaml .Values.livenessProbe | trimSuffix "\n" | indent 12 }}
          {{- end }}
          {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | trimSuffix "\n" | indent 12 }}
          {{- end }}
